---
# defaults file for powervc_vm_create
vm_name: ibmi_demo
vm_hostname: neo143
vm_group: ibmi_demos
image_name: ibmi-demo
nics:
  - net_name: Demo-pub
flavor_name: lj
userdata: '|
      {%- raw -%}#!/bin/sh
      system "crtusrprf usrprf(test) password(testpwd) status(*enabled) usrcls(*secofr) spcaut(*allobj *iosyscfg *jobctl *secadm *audit *service *splctl *savsys)"
      system "chgtcpsvr svrspcval(*sshd) autostart(*yes)"  
      system "strtcpsvr *sshd"
      {% endraw %}'

# Network Provisioning method
# Possible values are 'direct' for SRIOV and 'normal' for SEA
vm_create_binding_vnic_type: 'direct'

vm_create_port_binding_profile: "capacity='0.02', delete_with_instance='1', vnic_required_vfs='2'"
