---
- name: IBM i VM initalization
  hosts: localhost

  vars:
    #PowerVC and OpenStack variables:      
    cloud_name: 'pvcmop'
    vm_name: 'iTeamX'
    vm_hostname: 'iteamX' 
    availability_zone: "Radar:900922A_78DC790"
    image: 'IBMI-74TR7'
    compute_template: 'IBMi'
    nics:
      - net-name: "rubystudents361"
    vm_group: "Demo-ibmi"
    vm_create_binding_vnic_type: "direct"
    user_data: |
      {%- raw -%}#!/bin/sh
      system "chgusrprf usrprf(qciuser) password(passw0rd) status(*enabled) usrcls(*secofr) spcaut(*allobj *iosyscfg *jobctl *secadm *audit *service *splctl *savsys)"
      system "chgtcpsvr svrsrcval(*sshd) autostart(*yes)"  
      system "strtcpsvr *sshd"
      {% endraw %}
    compute_template: 'IBMi' 

  roles:
    - role: vm_create

  tasks:
    - name: Add VM to Ansible in-memory inventory
      add_host:
        #name: "{{ server_info.openstack.public_v4 }}"
        name: "{{ server_info.server.addresses.rubystudents361.0.addr }}"
        ansible_user: qciuser 
        ansible_ssh_pass: passw0rd
        groups: new_vm
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
        ansible_python_interpreter: /QOpensys/pkgs/bin/python2

- name: Verify connection to VM
  hosts: new_vm
  gather_facts: False
  tasks:
    - name: Wait for VM to become reachable over SSH
      wait_for_connection:
        delay: 240
