---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:

    - name: Copy XH2 SAVF to Ansible library
      ibmi_copy:
        src: 'xh2.savf'
        lib_name: 'ANSIBLE'
        force: True
      register: copy
    - debug:
       var: copy
