---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    
    - name: create user profile xxxxx
      ibmi_user_and_group:
        operation: 'create'
        user: 'xxxxx'
        user_class: '*SECOFR'
      register: user_result
      ignore_errors: true  
    - debug:
       var: user_result

    - name: display user profile xxxxx
      ibmi_user_and_group:
        operation: 'display'
        user: 'xxxxx'
      register: user_prof_info
    - debug:
       var: user_prof_info     
